### ISSUE TITLE
Parse server npm start error

### ISSUE THREAD

**Issue by lanma** [lanma/blog#1]
npm start

> my-parse-app@0.0.0 start /Users/mac/RD/NodeJs/Project/my-parse-app
> node ./bin/www

/Users/mac/RD/NodeJs/Project/my-parse-app/routes/index.js:5
router.get('/', function(req, res, next) {
      ^

TypeError: Cannot read property 'get' of undefined
    at Object.<anonymous> (/Users/mac/RD/NodeJs/Project/my-parse-app/routes/index.js:5:7)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/mac/RD/NodeJs/Project/my-parse-app/app.js:8:14)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! my-parse-app@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-parse-app@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the my-parse-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls my-parse-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mac/RD/NodeJs/Project/my-parse-app/npm-debug.log

**Comment by lanma** [comment]
npm install
