### ISSUE TITLE
Post Error Message

### ISSUE THREAD

**Issue by lanma** [lanma/blog#2]
Not Found

404

Error: Not Found
    at /Users/mac/RD/NodeJs/Project/ParseServerWotcityTest/app.js:42:13
    at Layer.handle [as handle_request](/Users/mac/RD/NodeJs/Project/ParseServerWotcityTest/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/mac/RD/NodeJs/Project/ParseServerWotcityTest/node_modules/express/lib/router/index.js:312:13)
    at /Users/mac/RD/NodeJs/Project/ParseServerWotcityTest/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/mac/RD/NodeJs/Project/ParseServerWotcityTest/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/mac/RD/NodeJs/Project/ParseServerWotcityTest/node_modules/express/lib/router/index.js:271:10)
    at /Users/mac/RD/NodeJs/Project/ParseServerWotcityTest/node_modules/express/lib/router/index.js:618:15
    at next (/Users/mac/RD/NodeJs/Project/ParseServerWotcityTest/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/Users/mac/RD/NodeJs/Project/ParseServerWotcityTest/node_modules/express/lib/router/index.js:176:3)
    at router (/Users/mac/RD/NodeJs/Project/ParseServerWotcityTest/node_modules/express/lib/router/index.js:46:12)

**Comment by lanma** [comment]
app.use('/parse', api);
需在404之前
